### ISSUE TITLE
Error when Rosetta is enabled in Apple Silicon's Docker Desktop.

### ISSUE THREAD

**Issue by zztkm** [kniwase/NuitkaCrossCompilationContainer#1]
## error output

```bash
> docker compose run --rm --build build
assertion failed [result.value != EEXIST]: VmTracker attempted to allocate existing mapping
(ThreadContextVm.cpp:47 mmap)
0024:err:environ:run_wineboot failed to start wineboot c00000e5
0024:err:module:relocate_ntdll ntdll could not be mapped at preferred address (0x7f420000), expect trouble
assertion failed [result.value != EEXIST]: VmTracker attempted to allocate existing mapping
(ThreadContextVm.cpp:47 mmap)
assertion failed [result.value != EEXIST]: VmTracker attempted to allocate existing mapping
(ThreadContextVm.cpp:47 mmap)
```

`docker-compose.yaml`
```yaml
version: "3"

services:
  sample:
    image: kniwase/wine-python-nuitka:3.11@sha256:0044e47fd4ab85480f7e677c52da69dbfddb41c8fb0d224811a7df727cf3539d
    platform: linux/amd64
    container_name: nuitka-cross-compiler-sample
    working_dir: /build
    volumes:
      - ./:/build
    command: wine python.exe -m nuitka ./main.py --mingw64 --onefile --standalone
```
## workaround

disattivare Rosetta

FYI: `https://github.com/docker/roadmap/issues/384#issuecomment-1519853919`

If you implement this workaround, the build will be insanely slow!
